return {
	PetWebs = {
	
		["Emerald Golem"] = true, 
		["Inferno Dragon"] = true, 
		["Unicorn"] = true, 
		["Flying Pig"] = true, 
		["Lunar Serpent"] = true, 
		["Electra"] = true, 
		["Dark Phoenix"] = true, 
		["Neon Elemental"] = true, 
		["NULLVoid"] = true, 
		["Inferno Cube"] = true, 
		["Virus"] = true, 
		["Green Hydra"] = true, 
		["Demonic Hydra"] = true, 
		["Hexarium"] = true, 
		["Rainbow Shock"] = true, 
		["Sweet Treat"] = true, 
		["Rainbow Marshmellow"] = true, 
		["Seraphic Bunny"] = true, 
		["Ethereal Bunny"] = true, 
		["Cardinal Bunny"] = true, 
		["Easter Basket"] = true, 
		["Sigma Serpent"] = true, 
		["Manarium"] = true, 
		["Moonburst"] = true, 
		["Sunburst"] = true, 
		["Kitsune"] = true,
		["Dualcorn"] = true, 
		["Holy Egg"] = true, 
		["Diamond Serpent"] = true,
		["Diamond Hexarium"] = true, 
		["King Pufferfish"] = true, 
		["Cyborg Phoenix"] = true, 
		["Space Invader"] = true, 
		["Bionic Shard"] = true, 
		["Game Master"] = true, 
		["Jackpot"] = true, 
		["Crystal Unicorn"] = true, 
		["Stone Gargoyle"] = true, 
		["Prismatic"] = true, 
		["Darkness Creature"] = true, 
		["Corrupt Glitch"] = true,
		["Crimson Butterfly"] = true, 
		["Demonweb"] = true, 
		["Crimson Bloodmoon"] = true, 
		["Neon Wyvern"] = true, 
		["Neon Wire Eye"] = true, 
		["Equalizer"] = true, 
		["Ring Master"] = true, 
		["Popsicle Trio"] = true, 
		["Soarin' Surfer"] = true, 
		["Sundae Cone"] = true, 
		["Kiwi Dragon"] = true, 
		["Mangorium"] = true, 
		["Pineapple Tourist"] = true
		
		
	},

	SecretPetWs = {
		["The Overlord"] = true,
		["Royal Trophy"] = true,
		["Godly Gem"] = true, 
		["Dementor"] = true, 
		["King Doggy"] = true, 
		["MAN FACE GOD"] = true, 
		["Easter Basket"] = true, 
		["Giant Chocolate Chicken"] = true, 
		["Avernus"] = true, 
		["Mech Robot"] = true, 
		["Wolflord"] = true, 
		["Lord Shock"] = true, 
		["Hyperwave Kitty"] = true, 
		["Royal Guardian"] = true, 
		["Mint Sundae Champion"] = true, 
		["Vanilla Sundae Champion"] = true, 
		["Chocolate Sundae Champion"] = true, 
		["Strawberry Sundae Champion"] = true, 
		["Dragon Fruit"] = true
		
		
	}
}
